server:
  port: 8080

spring:
  application:
    name: "maps"
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5435/mapsDb
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
          useInsecureTrustManager: true
          issuer-uri: http://localhost:7080/realms/master
      client:
        registration:
          keycloak:
            client-id: maps-microservice
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:7080/realms/master
            user-name-attribute: preferred_username
logging:
  level:
    org:
      springframework:
        security: DEBUG
        
info:
  app:
    info: "Maps microservice"
    
management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/